name: listadecoisa
description: App simples para todo tipo de listas.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+25

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.4.6
  fluttertoast: ^8.0.9
  firebase_auth: ^3.7.0
  translator: ^0.1.7
  google_mobile_ads: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  google_sign_in: ^5.4.1
  uni_links: ^0.5.1
  scan: ^1.6.0
  qr_flutter: ^4.0.0
  share: ^2.0.4
  hive: 2.0.6
  hive_flutter: ^1.1.0
  package_info_plus: ^1.4.3+1
  currency_text_input_formatter: ^2.1.7
  firebase_core: ^1.21.1
  get_it: ^7.2.0
  path: ^1.8.2
  path_provider: ^2.0.11
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  image: assets/test.png
  color: "FF406F"
  android_disable_fullscreen: false
  fill: false
# flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"

# flutter pub run flutter_native_splash:create
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

